# Generated by Django 3.1.6 on 2021-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210217_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='excerpt',
            field=models.CharField(max_length=100),
        ),
    ]
